### ISSUE TITLE
npm is unable to install `rollup-plugin-minify-template-literals@>=1.1.5`

### ISSUE THREAD

**Issue by malobre** [explodingcamera/esm#4]
Trying to install `rollup-plugin-minify-template-literals@>=1.1.5` with `npm` (`10.5.0`) fails:
```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

`rollup-plugin-minify-template-literals@=1.1.4` works fine.

**Comment by explodingcamera** [comment]
:+1: Should be be fixed in v1.1.7, there were some issues with the bundler.
